#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
$busybox mount -o remount,rw /
$busybox mount -o remount,rw rootfs
$busybox mount -o remount,rw /system

if [ "`pgrep media`" ] && [ "`pgrep mediaserver`" ]; then
	$busybox killall -9 android.process.media
	$busybox killall -9 mediaserver
fi