#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

echo "";
echo "*********************************************";
echo "Optimizing and defragging your database files (*.db)";
echo "*********************************************";
echo "";

for i in \
`$busybox find /data -iname "*.db"`; 
do \
	/system/SystemTweaker/sqlite3 $i 'VACUUM;'; 
	/system/SystemTweaker/sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`$busybox find /dbdata -iname "*.db"`; 
	do \
		/system/SystemTweaker/sqlite3 $i 'VACUUM;'; 
		/system/SystemTweaker/sqlite3 $i 'REINDEX;'; 
	done;
fi;


if [ -d "/datadata" ]; then
	for i in \
	`$busybox find /datadata -iname "*.db"`; 
	do \
		/system/SystemTweaker/sqlite3 $i 'VACUUM;'; 
		/system/SystemTweaker/sqlite3 $i 'REINDEX;'; 
	done;
fi;


for i in \
`$busybox find /sdcard -iname "*.db"`; 
do \
	/system/SystemTweaker/sqlite3 $i 'VACUUM;'; 
	/system/SystemTweaker/sqlite3 $i 'REINDEX;'; 
done;