#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o remount,rw / 2>/dev/null
mount -o remount,rw / / 2>/dev/null
mount -o remount,rw rootfs 2>/dev/null
mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system /system 2>/dev/null
$busybox mount -o remount,rw / 2>/dev/null
$busybox mount -o remount,rw / / 2>/dev/null
$busybox mount -o remount,rw rootfs 2>/dev/null
$busybox mount -o remount,rw /system 2>/dev/null
$busybox mount -o remount,rw /system /system 2>/dev/null

$busybox echo "Activating heavy kernel tweaks.." 

# Kernel_tweaks
$busybox sysctl -w kernel.msgmni=32768
$busybox sysctl -w kernel.msgmax=8192
$busybox sysctl -w kernel.msgmnb=16384
$busybox sysctl -w kernel.shmmni=4096
$busybox sysctl -w kernel.shmall=2097152
$busybox sysctl -w kernel.shmmax=268435456
$busybox sysctl -w kernel.sem='250 32000 100 128'

if [ -e /sys/kernel/dyn_fsync/Dyn_fsync_active ]; then
$busybox echo "1" > /sys/kernel/dyn_fsync/Dyn_fsync_active
fi
if grep 1 /sys/kernel/dyn_fsync/Dyn_fsync_active; then
$busybox echo "Dyn_fsync enabled"
else
$busybox echo "Dyn_fsync doesn't exist on your kernel" 
fi

#FS tweak
$busybox sysctl -w fs.lease-break-time=5
$busybox sysctl -w fs.inotify.max_queued_events=32768
$busybox sysctl -w fs.inotify.max_user_instances=256
$busybox sysctl -w fs.inotify.max_user_watches=16384

$busybox echo "File system parameters are updated"

# VM tweak
mem=\$((\$($busybox awk '/MemTotal/{print \$2}' /proc/meminfo)))
MFK=\$((mem*3/1024))

$busybox chmod 644 /proc/sys/vm/*
$busybox sysctl -w vm.dirty_expire_centisecs=500
$busybox sysctl -w vm.dirty_writeback_centisecs=3000
$busybox sysctl -w vm.block_dump=0
$busybox sysctl -w vm.laptop_mode=0
$busybox sysctl -w vm.min_free_kbytes=\$MFK
$busybox sysctl -w vm.min_free_order_shift=4
$busybox sysctl -w vm.oom_dump_tasks=1
$busybox sysctl -w vm.page-cluster=2
$busybox sysctl -w vm.dirty_background_ratio=20
$busybox sysctl -w vm.dirty_ratio=40
if [ -e /sys/block/zram* ]; then
		$busybox sysctl -w vm.swappiness=40
      else
		$busybox sysctl -w vm.swappiness=20
fi

$busybox echo "Heavy kernel tweaks are activated"

mount -o remount,ro / 2>/dev/null
mount -o remount,ro / / 2>/dev/null
mount -o remount,ro rootfs 2>/dev/null
mount -o remount,ro /system 2>/dev/null
mount -o remount,ro /system /system 2>/dev/null
$busybox mount -o remount,ro / 2>/dev/null
$busybox mount -o remount,ro / / 2>/dev/null
$busybox mount -o remount,ro rootfs 2>/dev/null
$busybox mount -o remount,ro /system 2>/dev/null
$busybox mount -o remount,ro /system /system 2>/dev/null