#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

path=`$busybox ls -d /sys/block/* 2>/dev/null`;
for S in $path;
do
	if [ -e $S/queue/iostats ]; then
		$busybox echo "0" > $S/queue/iostats
	fi
	if [ -e $S/queue/add_random ]; then
		$busybox echo "0" > $S/queue/add_random
	fi
	if [ -e $S/queue/nr_requests ]; then
		$busybox echo "256" > $S/queue/nr_requests
	fi
	if [ -e $S/queue/nomerges ]; then
		$busybox echo "1" > $S/queue/nomerges
	fi
	if [ -e $S/queue/iosched/low_latency ]; then
		$busybox echo "0" > $S/queue/iosched/slice_idle;
		$busybox echo "0" > $S/queue/iosched/max_budget;
	fi
done

$busybox echo "I/O speed tweak"