#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
$busybox mount -o remount,rw /
$busybox mount -o remount,rw rootfs
$busybox mount -o remount,rw /system


# Kernel sleepers
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_AFFINE_WAKEUPS" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_ARCH_POWER" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_CACHE_HOT_BUDDY" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_DOUBLE_TICK" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_FORCE_SD_OVERLAP" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_GENTLE_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_HRTICK" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_LAST_BUDDY" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_LB_BIAS" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_LB_MIN" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_NEW_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_NEXT_BUDDY" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_NONTASK_POWER" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_NORMALIZED_SLEEPERS" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_OWNER_SPIN" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_RT_RUNTIME_SHARE" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_START_DEBIT" >> /sys/kernel/debug/sched_features
	$busybox echo "NO_TTWU_QUEUE" >> /sys/kernel/debug/sched_features
fi

$busybox echo "Kernel sleepers applied"
