#!/data/data/com.nowenui.systemtweaker/files/ash

busybox=/data/data/com.nowenui.systemtweaker/files/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null


# Kernel sleepers
mount -t debugfs none /sys/kernel/debug
$busybox mount -t debugfs none /sys/kernel/debug
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_AFFINE_WAKEUPS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_ARCH_POWER" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_CACHE_HOT_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_DOUBLE_TICK" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_FORCE_SD_OVERLAP" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_GENTLE_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_HRTICK" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LAST_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LB_BIAS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LB_MIN" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NEW_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NEXT_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NONTASK_POWER" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NORMALIZED_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_OWNER_SPIN" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_RT_RUNTIME_SHARE" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_START_DEBIT" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_TTWU_QUEUE" >> /sys/kernel/debug/sched_features
fi

$busybox umount /sys/kernel/debug

$busybox echo "Kernel sleepers applied"
