#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o remount,rw / 2>/dev/null
mount -o remount,rw / / 2>/dev/null
mount -o remount,rw rootfs 2>/dev/null
mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system /system 2>/dev/null
$busybox mount -o remount,rw / 2>/dev/null
$busybox mount -o remount,rw / / 2>/dev/null
$busybox mount -o remount,rw rootfs 2>/dev/null
$busybox mount -o remount,rw /system 2>/dev/null
$busybox mount -o remount,rw /system /system 2>/dev/null

$busybox echo "Activating light kernel tweaks.."

# Kernel_tweaks
if [ -e /sys/kernel/dyn_fsync/Dyn_fsync_active ]; then
$busybox echo "1" > /sys/kernel/dyn_fsync/Dyn_fsync_active
fi
if grep 1 /sys/kernel/dyn_fsync/Dyn_fsync_active; then
$busybox echo "Dyn_fsync enabled"
else
$busybox echo "Dyn_fsync doesn't exist on your kernel"
fi

#FS tweak
$busybox sysctl -w fs.lease-break-time=8
$busybox sysctl -w fs.inotify.max_queued_events=32768
$busybox sysctl -w fs.inotify.max_user_instances=256
$busybox sysctl -w fs.inotify.max_user_watches=16384

$busybox echo "File system parameters are updated" 

mem=$(($($busybox awk '/MemTotal/{print \$2}' /proc/meminfo)))
MFK=$((mem*3/1024))

$busybox chmod 644 /proc/sys/vm/*
$busybox sysctl -w vm.block_dump=0
$busybox sysctl -w vm.laptop_mode=0
$busybox sysctl -w vm.min_free_kbytes=\$MFK
$busybox sysctl -w vm.min_free_order_shift=4
$busybox sysctl -w vm.oom_dump_tasks=1
$busybox sysctl -w vm.page-cluster=2
if [ "$mem" -lt 524288 ]; then
    $busybox sysctl -w vm.dirty_background_ratio=15
    $busybox sysctl -w vm.dirty_ratio=30
elif [ "$mem" -lt 1048576 ]; then
    $busybox sysctl -w vm.dirty_background_ratio=10
    $busybox sysctl -w vm.dirty_ratio=20
  else
    $busybox sysctl -w vm.dirty_background_ratio=5
    $busybox sysctl -w vm.dirty_ratio=10
fi
if [ -e /sys/block/zram* ]; then
		$busybox sysctl -w vm.swappiness=40
      else
		$busybox sysctl -w vm.swappiness=20
fi

$busybox echo "Light kernel tweaks are activated"

mount -o remount,ro / 2>/dev/null
mount -o remount,ro / / 2>/dev/null
mount -o remount,ro rootfs 2>/dev/null
mount -o remount,ro /system 2>/dev/null
mount -o remount,ro /system /system 2>/dev/null
$busybox mount -o remount,ro / 2>/dev/null
$busybox mount -o remount,ro / / 2>/dev/null
$busybox mount -o remount,ro rootfs 2>/dev/null
$busybox mount -o remount,ro /system 2>/dev/null
$busybox mount -o remount,ro /system /system 2>/dev/null
