#!/data/data/com.nowenui.systemtweaker/files/ash

busybox=/data/data/com.nowenui.systemtweaker/files/busybox

clear

echo -e "###############  NowenUI Boost script  #############"
echo -e "####################################################"
echo -e "########          For System Tweaker     ###########"
echo -e "####################################################"


$busybox echo "		Mounting FS..... OK"
mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
$busybox mount -o remount,rw /
$busybox mount -o remount,rw rootfs
$busybox mount -o remount,rw /system
$busybox mount -o rw,remount /data
$busybox mount -o rw,remount /system
$busybox mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null

#boosting RAM
$busybox echo "		RAM BOOST..... OK"
echo "3" > /proc/sys/vm/drop_caches
sleep 3
echo "1" > /proc/sys/vm/drop_caches

#SQLite
for i in \
`$busybox find /data -iname "*.db"`; 
do \
	/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'VACUUM;'; 
	/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`$busybox find /dbdata -iname "*.db"`; 
	do \
		/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'VACUUM;'; 
		/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'REINDEX;'; 
	done;
fi;


if [ -d "/datadata" ]; then
	for i in \
	`$busybox find /datadata -iname "*.db"`; 
	do \
		/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'VACUUM;'; 
		/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'REINDEX;'; 
	done;
fi;


for i in \
`$busybox find /sdcard -iname "*.db"`; 
do \
	/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'VACUUM;'; 
	/data/data/com.nowenui.systemtweaker/files/sqlite3 $i 'REINDEX;'; 
done;

# Cleaner
$busybox echo "		Cleaning junk files..... OK"
$B chmod 777 -R /cache;
$B rm -f /cache/*.apk;
$B rm -f /cache/*.tmp;
$B rm -f /cache/*.log;
$B rm -f /cache/*.txt;
$B rm -Rf /cache/recovery;
$B rm -Rf /cache/backup;
$B rm -Rf /cache/lost+found;
$B rm -f /data/*.log;
$B rm -f /data/*.txt;
$B rm -f /data/anr/*.log;
$B rm -f /data/anr/*.txt;
$B rm -f /data/backup/pending/*.tmp;
$B rm -f /data/cache/*.*;
$B rm -f /data/data/*.log;
$B rm -f /data/data/*.txt;
$B rm -f /data/dalvik-cache/*.apk;
$B rm -f /data/dalvik-cache/*.tmp;
$B rm -f /data/log/*.log;
$B rm -f /data/log/*.txt;
$B rm -f /data/local/*.apk;
$B rm -f /data/local/*.log;
$B rm -f /data/local/*.txt;
$B rm -f /data/local/tmp/*.log;
$B rm -f /data/last_alog/*.log;
$B rm -f /data/last_alog/*.txt;
$B rm -f /data/last_kmsg/*.log;
$B rm -f /data/last_kmsg/*.txt;
$B rm -f /data/system/*.log;
$B rm -f /data/system/*.txt;
$B rm -Rf /sdcard/LOST.DIR;
$B rm -f /sdcard/*.log;
pm trim-caches 16g;
pm trim-caches 128g;

#fstrim
$busybox echo "		FSTRIM..... OK"
$busybox fstrim -v /cache;
$busybox fstrim -v /data;
$busybox fstrim -v /system;

# Boosting profily (balanced)
$busybox echo "		Enabling balanced profile...... OK"

if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
$busybox echo "32" > /sys/module/lowmemorykiller/parameters/cost
fi
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
$busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
fi
mem=`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`
RAM=$((`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`/1024))
oom11=$(($RAM*2/100));
oom21=$(($RAM*3/100));
oom31=$(($RAM*5/100));
oom41=$(($RAM*9/100));
oom51=$(($RAM*10/100));
oom61=$(($RAM*11/100));
lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));
oom12=$(($RAM*2/100));
oom22=$(($RAM*3/100));
oom32=$(($RAM*5/100));
oom42=$(($RAM*9/100));
oom52=$(($RAM*10/100));
oom62=$(($RAM*11/100));
lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));
oom13=$(($RAM*2/100));
oom23=$(($RAM*3/100));
oom33=$(($RAM*5/100));
oom43=$(($RAM*9/100));
oom53=$(($RAM*10/100));
oom63=$(($RAM*11/100));
lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));
oom14=$(($RAM*2/100));
oom24=$(($RAM*3/100));
oom34=$(($RAM*5/100));
oom44=$(($RAM*9/100));
oom54=$(($RAM*10/100));
oom64=$(($RAM*11/100));
lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));
oom15=$(($RAM*2/100));
oom25=$(($RAM*3/100));
oom35=$(($RAM*5/100));
oom45=$(($RAM*9/100));
oom55=$(($RAM*10/100));
oom65=$(($RAM*11/100));
lmk15=$(($oom15*1024/4));
lmk25=$(($oom25*1024/4));
lmk35=$(($oom35*1024/4));
lmk45=$(($oom45*1024/4));
lmk55=$(($oom55*1024/4));
lmk65=$(($oom65*1024/4));
oom16=$(($RAM*2/100));
oom26=$(($RAM*3/100));
oom36=$(($RAM*5/100));
oom46=$(($RAM*9/100));
oom56=$(($RAM*10/100));
oom66=$(($RAM*11/100));
lmk16=$(($oom16*1024/4));
lmk26=$(($oom26*1024/4));
lmk36=$(($oom36*1024/4));
lmk46=$(($oom46*1024/4));
lmk56=$(($oom56*1024/4));
lmk66=$(($oom66*1024/4));
oom17=$(($RAM*2/100));
oom27=$(($RAM*3/100));
oom37=$(($RAM*5/100));
oom47=$(($RAM*9/100));
oom57=$(($RAM*10/100));
oom67=$(($RAM*11/100));
lmk17=$(($oom17*1024/4));
lmk27=$(($oom27*1024/4));
lmk37=$(($oom37*1024/4));
lmk47=$(($oom47*1024/4));
lmk57=$(($oom57*1024/4));
lmk67=$(($oom67*1024/4));
if [ "$mem" -lt 524288 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 786432 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1048576 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1572864 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 2097152 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk15,$lmk25,$lmk35,$lmk45,$lmk55,$lmk65" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 3145728 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk16,$lmk26,$lmk36,$lmk46,$lmk56,$lmk66" > /sys/module/lowmemorykiller/parameters/minfree
else 
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk17,$lmk27,$lmk37,$lmk47,$lmk57,$lmk67" > /sys/module/lowmemorykiller/parameters/minfree
fi


# Internet booster
$busybox echo "		Internet boosting..... OK"
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "404480" > /proc/sys/net/core/wmem_max;
echo "404480" > /proc/sys/net/core/rmem_max;
echo "256960" > /proc/sys/net/core/rmem_default;
echo "256960" > /proc/sys/net/core/wmem_default;
echo "4096,16384,404480" > /proc/sys/net/ipv4/tcp_wmem;
echo "4096,87380,404480" > /proc/sys/net/ipv4/tcp_rmem;

# Kernel tweaks
$busybox echo "		Tweaking kernel..... OK"
echo "8" > /proc/sys/vm/page-cluster;
echo "64000" > /proc/sys/kernel/msgmni;
echo "64000" > /proc/sys/kernel/msgmax;
echo "10" > /proc/sys/fs/lease-break-time;
echo "500,512000,64,2048" > /proc/sys/kernel/sem;

# Battery  Tweaks
$busybox echo "		Tweaking battery..... OK"
echo "500" > /proc/sys/vm/dirty_expire_centisecs
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs

#VMTweaks
$busybox echo "		VM tweaking..... OK"
echo "4096" > /proc/sys/vm/min_free_kbytes
echo "0" > /proc/sys/vm/oom_kill_allocating_task;
echo "0" > /proc/sys/vm/panic_on_oom;
echo "0" > /proc/sys/vm/laptop_mode;
echo "0" > /proc/sys/vm/swappiness
echo "50" > /proc/sys/vm/vfs_cache_pressure
echo "90" > /proc/sys/vm/dirty_ratio
echo "70" > /proc/sys/vm/dirty_background_ratio

# SDcard tweaker
$busybox echo "		SdCard tweaking..... OK"
$busybox sleep 5
READ_AHEAD_KB="2048"
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:8/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:8/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:16/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:16/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:24/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:24/read_ahead_kb
fi
if [ -e /system/bin/make_ext4fs ]; then
    mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /cache /cache
    mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /data /data
fi
if [ -e /proc/sys/vm/panic_on_oom ]; then
    echo "3" > /proc/sys/vm/panic_on_oom
fi
if [ -e /proc/sys/vm/stat_interval ]; then
    echo "1" > /proc/sys/vm/stat_interval
fi
if [ -e /proc/sys/vm/mmap_min_addr ]; then
    echo "0" > /proc/sys/vm/mmap_min_addr
fi
if [ -e /proc/sys/vm/overcommit_memory ]; then
    echo "1" > /proc/sys/vm/overcommit_memory
fi
if [ -e /proc/sys/vm/min_free_kbytes ]; then
    echo "16384" > /proc/sys/vm/min_free_kbytes
fi
if [ -e /proc/sys/vm/min_free_order_shift ]; then
    echo "5" > /proc/sys/vm/min_free_order_shift
fi
if [ -e /proc/sys/vm/highmem_is_dirtyable ]; then
    echo "1" > /proc/sys/vm/highmem_is_dirtyable
fi
if [ -e /proc/sys/vm/scan_unevictable_pages ]; then
    echo "0" > /proc/sys/vm/scan_unevictable_pages
fi
if [ -e /proc/sys/vm/oom_kill_allocating_task ]; then
    echo "1" > /proc/sys/vm/oom_kill_allocating_task
fi
if [ -e /proc/sys/vm/dirty_background_ratio ]; then
    echo "0" > /proc/sys/vm/dirty_background_ratio
fi
if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
    echo "1000" > /proc/sys/vm/dirty_expire_centisecs
fi
if [ -e /proc/sys/vm/dirty_ratio ]; then
    echo "10" > /proc/sys/vm/dirty_ratio
fi
if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
    echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
fi
if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
    echo "40" > /proc/sys/vm/vfs_cache_pressure
fi

#Disabling ZRAM
swapoff /dev/block/zram0 > /dev/null 2>&1
echo "0" > /sys/block/zram0/disksize
echo "1" > /sys/block/zram0/reset
setprop ro.config.zram false
echo "0" > /proc/sys/vm/swappiness 


#I/O
path=`$busybox ls -d /sys/block/* 2>/dev/null`;
for S in $path;
do
	if [ -e $S/queue/iostats ]; then
		$busybox echo "0" > $S/queue/iostats
	fi
	if [ -e $S/queue/add_random ]; then
		$busybox echo "0" > $S/queue/add_random
	fi
done