#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

$busybox sysctl -e -w vm.oom_dump_tasks=1
$busybox sysctl -e -w vm.oom_kill_allocating_task=1

$busybox echo "OOM killer enabled.."
