#!/system/SystemTweaker/ash

busybox=/system/SystemTweaker/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
$busybox echo "32" > /sys/module/lowmemorykiller/parameters/cost
fi

# Debug level
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
$busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
fi

# Minfree Values 
mem=`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`
RAM=$((`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`/1024))

#512 and less
oom11=$(($RAM*2/100));
oom21=$(($RAM*3/100));
oom31=$(($RAM*5/100));
oom41=$(($RAM*9/100));
oom51=$(($RAM*10/100));
oom61=$(($RAM*11/100));

lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));

#768
oom12=$(($RAM*2/100));
oom22=$(($RAM*3/100));
oom32=$(($RAM*5/100));
oom42=$(($RAM*9/100));
oom52=$(($RAM*10/100));
oom62=$(($RAM*11/100));

lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));

#1024
oom13=$(($RAM*2/100));
oom23=$(($RAM*3/100));
oom33=$(($RAM*5/100));
oom43=$(($RAM*9/100));
oom53=$(($RAM*10/100));
oom63=$(($RAM*11/100));

lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));

#1536
oom14=$(($RAM*2/100));
oom24=$(($RAM*3/100));
oom34=$(($RAM*5/100));
oom44=$(($RAM*9/100));
oom54=$(($RAM*10/100));
oom64=$(($RAM*11/100));

lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));

#2048
oom15=$(($RAM*2/100));
oom25=$(($RAM*3/100));
oom35=$(($RAM*5/100));
oom45=$(($RAM*9/100));
oom55=$(($RAM*10/100));
oom65=$(($RAM*11/100));

lmk15=$(($oom15*1024/4));
lmk25=$(($oom25*1024/4));
lmk35=$(($oom35*1024/4));
lmk45=$(($oom45*1024/4));
lmk55=$(($oom55*1024/4));
lmk65=$(($oom65*1024/4));

#3072
oom16=$(($RAM*2/100));
oom26=$(($RAM*3/100));
oom36=$(($RAM*5/100));
oom46=$(($RAM*9/100));
oom56=$(($RAM*10/100));
oom66=$(($RAM*11/100));

lmk16=$(($oom16*1024/4));
lmk26=$(($oom26*1024/4));
lmk36=$(($oom36*1024/4));
lmk46=$(($oom46*1024/4));
lmk56=$(($oom56*1024/4));
lmk66=$(($oom66*1024/4));

#4096+
oom17=$(($RAM*2/100));
oom27=$(($RAM*3/100));
oom37=$(($RAM*5/100));
oom47=$(($RAM*9/100));
oom57=$(($RAM*10/100));
oom67=$(($RAM*11/100));

lmk17=$(($oom17*1024/4));
lmk27=$(($oom27*1024/4));
lmk37=$(($oom37*1024/4));
lmk47=$(($oom47*1024/4));
lmk57=$(($oom57*1024/4));
lmk67=$(($oom67*1024/4));

if [ "$mem" -lt 524288 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 786432 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1048576 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1572864 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 2097152 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk15,$lmk25,$lmk35,$lmk45,$lmk55,$lmk65" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 3145728 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk16,$lmk26,$lmk36,$lmk46,$lmk56,$lmk66" > /sys/module/lowmemorykiller/parameters/minfree
else 
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk17,$lmk27,$lmk37,$lmk47,$lmk57,$lmk67" > /sys/module/lowmemorykiller/parameters/minfree
fi
